# Generated by Django 6.1 on 2026-08-14 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='Investigator', max_length=50)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConsultationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceCustody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Evidence custody records',
                'ordering': ['transfer_date'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('item_type', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('IN_CUSTODY', 'In Custody'), ('TRANSFERRED', 'Transferred'), ('RELEASED', 'Released'), ('DISPOSED', 'Disposed')], default='IN_CUSTODY', max_length=20)),
                ('storage_location', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FIR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fir_number', models.CharField(max_length=50, unique=True)),
                ('complaint_date', models.DateField()),
                ('reporting_date', models.DateTimeField(auto_now_add=True)),
                ('complainant_name', models.CharField(max_length=255)),
                ('complainant_phone', models.CharField(blank=True, max_length=20)),
                ('complainant_address', models.TextField(blank=True)),
                ('crime_type', models.CharField(choices=[('THEFT', 'Theft'), ('ASSAULT', 'Assault'), ('BURGLARY', 'Burglary'), ('FRAUD', 'Fraud'), ('VANDALISM', 'Vandalism'), ('TRAFFIC', 'Traffic Violation'), ('CYBERCRIME', 'Cybercrime'), ('DRUG', 'Drug Offense'), ('DOMESTIC', 'Domestic Violence'), ('HOMICIDE', 'Homicide'), ('ROBBERY', 'Robbery'), ('OTHER', 'Other')], max_length=30)),
                ('crime_description', models.TextField()),
                ('incident_location', models.TextField()),
                ('incident_date', models.DateField()),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('UNDER_INVESTIGATION', 'Under Investigation'), ('CLOSED', 'Closed'), ('TRANSFERRED', 'Transferred')], default='OPEN', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FIR',
                'verbose_name_plural': 'FIRs',
                'ordering': ['-reporting_date'],
            },
        ),
        migrations.CreateModel(
            name='InvestigationNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('officer_name', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('note_type', models.CharField(default='PROGRESS', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_number', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('rank', models.CharField(choices=[('Constable', 'Constable'), ('Sergeant', 'Sergeant'), ('Inspector', 'Inspector'), ('Assistant Commissioner', 'Assistant Commissioner'), ('Deputy Commissioner', 'Deputy Commissioner'), ('Commissioner', 'Commissioner')], max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('unit', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['rank', 'full_name'],
            },
        ),
    ]
