# Generated by Django 6.1 on 2026-08-14 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='caseteammember',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='requestor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_consultations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='responder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_consultations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evidencecustody',
            name='evidence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custody_chain', to='cases.evidenceitem'),
        ),
        migrations.AddField(
            model_name='fir',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_firs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evidenceitem',
            name='fir',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_items', to='cases.fir'),
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='fir',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_requests', to='cases.fir'),
        ),
        migrations.AddField(
            model_name='caseteammember',
            name='fir',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='cases.fir'),
        ),
        migrations.AddField(
            model_name='investigationnote',
            name='fir',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='cases.fir'),
        ),
        migrations.AddField(
            model_name='investigationnote',
            name='officer_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fir',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_firs', to='cases.officer'),
        ),
        migrations.AddField(
            model_name='evidencecustody',
            name='received_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.officer'),
        ),
        migrations.AddField(
            model_name='evidencecustody',
            name='transferred_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferred_evidence', to='cases.officer'),
        ),
        migrations.AddField(
            model_name='caseteammember',
            name='officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_teams', to='cases.officer'),
        ),
        migrations.AlterUniqueTogether(
            name='caseteammember',
            unique_together={('fir', 'officer')},
        ),
    ]
