# Generated by Django 6.1 on 2026-08-14 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('role', models.CharField(choices=[('CLERK', 'Clerk'), ('INVESTIGATOR', 'Investigator'), ('STATION_COMMANDER', 'Station Commander'), ('ADMIN', 'Administrator')], default='CLERK', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('failed_attempts', models.IntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('officer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_account', to='cases.officer')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('action', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('LOGIN_FAILED', 'Login Failed'), ('VIEW_CASE', 'View Case'), ('CREATE_FIR', 'Create FIR'), ('UPDATE_CASE', 'Update Case'), ('DELETE_CASE', 'Delete Case'), ('TRANSFER_CASE', 'Transfer Case'), ('CLOSE_CASE', 'Close Case'), ('ADD_NOTE', 'Add Investigation Note'), ('ADD_TEAM_MEMBER', 'Add Team Member'), ('REMOVE_TEAM_MEMBER', 'Remove Team Member'), ('ADD_EVIDENCE', 'Add Evidence'), ('TRANSFER_EVIDENCE', 'Transfer Evidence'), ('REQUEST_CONSULTATION', 'Request Consultation'), ('APPROVE_CONSULTATION', 'Approve Consultation'), ('REJECT_CONSULTATION', 'Reject Consultation'), ('CREATE_USER', 'Create User'), ('UPDATE_USER', 'Update User'), ('DEACTIVATE_USER', 'Deactivate User'), ('MARK_ATTENDANCE', 'Mark Attendance'), ('APPROVE_LEAVE', 'Approve Leave'), ('REJECT_LEAVE', 'Reject Leave'), ('ASSIGN_DUTY', 'Assign Duty'), ('ADD_VEHICLE', 'Add Vehicle'), ('ASSIGN_VEHICLE', 'Assign Vehicle'), ('ADD_EQUIPMENT', 'Add Equipment'), ('EXPORT_REPORT', 'Export Report')], max_length=40)),
                ('model_type', models.CharField(blank=True, max_length=50)),
                ('object_id', models.CharField(blank=True, max_length=100)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Audit logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
